server:
  port: 8080
  context-path: /web
  session:
    timeout: 600

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 10MB
security:
  user:
    name: admin
    password: admin@123

pzx:
  social:
    weixin:
      app-id: wxd99431bbff8305a0
      app-secret: 60f78681d063590a469f1b297feff3c4


rongyun:
  appkey:
  appsecret:

