server:
  port: 8080
  context-path: /web
  session:
    timeout: 600

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.60.223:3306/test?useUnicode=true&useSSL=false
#    url: jdbc:mysql://47.93.60.223:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: GMT+8
security:
  user:
    name: admin
    password: admin@123

pzx:
  social:
    weixin:
      app-id: wxd99431bbff8305a0
      app-secret: 60f78681d063590a469f1b297feff3c4

gril:
  cupSize: B
  age: 18
